// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ODataProvider")>]
[<assembly: AssemblyProductAttribute("ODataTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("an F# type provider for OData resources")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ODataProvider"
    let [<Literal>] AssemblyProduct = "ODataTypeProvider"
    let [<Literal>] AssemblyDescription = "an F# type provider for OData resources"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
